development:
  adapter: postgresql
  encoding: unicode
  database: scoreboard_dev
  host: localhost
  pool: 5
  min_messages: warning

test:
  adapter: postgresql
  encoding: unicode
  database: scoreboard_test
  host: localhost
  pool: 5
  min_messages: warning
